import { POLICY_TEMPLATES } from "@/lib/policyTemplates";

const now = Date.now();
const isoMinutesAgo = (m) => new Date(now - m * 60_000).toISOString();
const isoDaysAgo = (d) => new Date(now - d * 24 * 60 * 60_000).toISOString();

export const SEED_AGENTS = [
  {
    id: "seed-agent-treasury",
    name: "treasury-rebalancer",
    description: "Keeps stablecoin allocation across L2s within target bands.",
    objective: "Rebalance USDC between Base and Arbitrum when drift > 5%.",
    chain: "base",
    status: "active",
    policy_id: "seed-policy-conservative",
    total_value_moved: 142_350,
    tx_count: 187,
    last_run_at: isoMinutesAgo(6),
    created_date: isoDaysAgo(14),
    updated_date: isoMinutesAgo(6),
  },
  {
    id: "seed-agent-yield",
    name: "yield-router",
    description: "Routes idle stables to the highest risk-adjusted APY pool.",
    objective: "Move stables to highest APY pool weekly, $5k caps.",
    chain: "arbitrum",
    status: "active",
    policy_id: "seed-policy-multichain-yield",
    total_value_moved: 89_120,
    tx_count: 64,
    last_run_at: isoMinutesAgo(48),
    created_date: isoDaysAgo(9),
    updated_date: isoMinutesAgo(48),
  },
  {
    id: "seed-agent-payroll",
    name: "vendor-payroll",
    description: "Disburses monthly vendor payments from an allowlist.",
    objective: "Pay 12 approved vendors USDC every 1st of the month.",
    chain: "base",
    status: "paused",
    policy_id: "seed-policy-allowlist",
    total_value_moved: 240_000,
    tx_count: 36,
    last_run_at: isoDaysAgo(3),
    created_date: isoDaysAgo(30),
    updated_date: isoDaysAgo(3),
  },
];

export const SEED_POLICIES = [
  {
    id: "seed-policy-conservative",
    name: "Treasury Conservative",
    description: "Tight per-tx limit and modest daily cap. USDC only on Base.",
    max_tx_value_usd: 250,
    daily_spend_limit_usd: 1000,
    require_human_approval_above_usd: 500,
    allowed_chains: ["base"],
    allowed_tokens: ["USDC"],
    allowed_contracts: [],
    is_active: true,
    created_date: isoDaysAgo(20),
    updated_date: isoDaysAgo(2),
  },
  {
    id: "seed-policy-multichain-yield",
    name: "Multichain Yield",
    description: "Generous daily cap across major L2s, stables only.",
    max_tx_value_usd: 10000,
    daily_spend_limit_usd: 50000,
    require_human_approval_above_usd: 15000,
    allowed_chains: ["base", "arbitrum", "optimism", "polygon"],
    allowed_tokens: ["USDC", "USDT", "DAI"],
    allowed_contracts: [],
    is_active: true,
    created_date: isoDaysAgo(15),
    updated_date: isoDaysAgo(4),
  },
  {
    id: "seed-policy-allowlist",
    name: "Vendor Allowlist",
    description: "Restricts transactions to a fixed recipient allowlist.",
    max_tx_value_usd: 5000,
    daily_spend_limit_usd: 25000,
    require_human_approval_above_usd: 2500,
    allowed_chains: ["base", "ethereum"],
    allowed_tokens: ["USDC", "USDT"],
    allowed_contracts: [
      "0x4200000000000000000000000000000000000006",
      "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    ],
    is_active: true,
    created_date: isoDaysAgo(30),
    updated_date: isoDaysAgo(7),
  },
];

const TX_TEMPLATES = [
  {
    agent_name: "treasury-rebalancer",
    action_type: "swap",
    chain: "base",
    token_symbol: "USDC",
    value_usd: 245.12,
    token_amount: 245.12,
    status: "success",
    policy_check: { passed: true, rule_triggered: "max_tx_value", reason: "Within $250 per-tx cap." },
    reasoning: "Drift detected: USDC pool below target weight by 4.8%. Bridging to restore.",
  },
  {
    agent_name: "treasury-rebalancer",
    action_type: "transfer",
    chain: "base",
    token_symbol: "USDC",
    value_usd: 180.0,
    token_amount: 180.0,
    status: "success",
    policy_check: { passed: true, rule_triggered: "daily_spend_limit", reason: "Daily limit unused." },
    reasoning: "Routine sweep into operating wallet.",
  },
  {
    agent_name: "yield-router",
    action_type: "deposit",
    chain: "arbitrum",
    token_symbol: "USDC",
    value_usd: 4_750.0,
    token_amount: 4_750.0,
    status: "success",
    policy_check: { passed: true, rule_triggered: "max_tx_value", reason: "Within $10k per-tx cap." },
    reasoning: "Aave aArb USDC reserve APY uplift exceeded threshold by 64bps.",
  },
  {
    agent_name: "yield-router",
    action_type: "swap",
    chain: "optimism",
    token_symbol: "USDT",
    value_usd: 12_400.0,
    token_amount: 12_400.0,
    status: "awaiting_approval",
    policy_check: { passed: false, rule_triggered: "require_human_approval", reason: "Above $15k approval threshold." },
    reasoning: "USDT yield window opening on Velodrome — flagged for review.",
  },
  {
    agent_name: "treasury-rebalancer",
    action_type: "swap",
    chain: "ethereum",
    token_symbol: "WETH",
    value_usd: 9_800.0,
    token_amount: 3.2,
    status: "policy_blocked",
    policy_check: { passed: false, rule_triggered: "allowed_chains", reason: "Ethereum is not in allowlist." },
    reasoning: "Hot opportunity on mainnet — blocked by policy guardrail.",
  },
  {
    agent_name: "vendor-payroll",
    action_type: "transfer",
    chain: "base",
    token_symbol: "USDC",
    value_usd: 8_500.0,
    token_amount: 8_500.0,
    status: "success",
    policy_check: { passed: true, rule_triggered: "allowed_contracts", reason: "Recipient on allowlist." },
    reasoning: "Monthly disbursement to Vendor #4 (consulting).",
  },
  {
    agent_name: "yield-router",
    action_type: "withdraw",
    chain: "polygon",
    token_symbol: "DAI",
    value_usd: 2_100.0,
    token_amount: 2_100.0,
    status: "success",
    policy_check: { passed: true },
    reasoning: "Position settled — APY dropped below 4% floor.",
  },
  {
    agent_name: "treasury-rebalancer",
    action_type: "transfer",
    chain: "base",
    token_symbol: "USDC",
    value_usd: 30.0,
    token_amount: 30.0,
    status: "failed",
    policy_check: { passed: true },
    reasoning: "Settlement reverted — RPC nonce conflict on retry.",
  },
];

export const SEED_TRANSACTIONS = TX_TEMPLATES.map((tx, i) => ({
  id: `seed-tx-${i + 1}`,
  tx_hash: `0x${(0xabcd1234 + i * 7919).toString(16).padStart(64, "0").slice(-64)}`,
  block_number: 18_240_000 - i * 17,
  from_address: "0x6f9d05a8e2b76e9b4f5e1a6c9d2b8e3a7c4d5f1e",
  to_address: "0x4200000000000000000000000000000000000006",
  gas_used_usd: 0.0142 + i * 0.0009,
  executed_at: isoMinutesAgo(8 + i * 23),
  created_date: isoMinutesAgo(8 + i * 23),
  updated_date: isoMinutesAgo(8 + i * 23),
  ...tx,
}));

export const SEED_AGENT_MESSAGES = [
  {
    id: "seed-msg-1",
    kind: "broadcast",
    agent_id: "seed-agent-treasury",
    agent_name: "treasury-rebalancer",
    subject: "Rebalance complete",
    body: "Restored USDC pool weight to 32% on Base.",
    target_agent_ids: [],
    created_date: isoMinutesAgo(12),
    updated_date: isoMinutesAgo(12),
  },
  {
    id: "seed-msg-2",
    kind: "verification_request",
    agent_id: "seed-agent-yield",
    agent_name: "yield-router",
    subject: "Approve $12.4k Velodrome deposit",
    body: "Pool APY 8.4%, IL risk low. Requesting concurrence before execution.",
    target_agent_ids: ["seed-agent-treasury", "seed-agent-payroll"],
    verification_status: "pending",
    thread_id: "seed-msg-2",
    created_date: isoMinutesAgo(7),
    updated_date: isoMinutesAgo(7),
  },
  {
    id: "seed-msg-3",
    kind: "status",
    agent_id: "seed-agent-payroll",
    agent_name: "vendor-payroll",
    subject: "Paused for month-end review",
    body: "Awaiting approval cohort sign-off before next disbursement run.",
    target_agent_ids: [],
    created_date: isoDaysAgo(2),
    updated_date: isoDaysAgo(2),
  },
];

export const SEED_ALERTS = [
  {
    id: "seed-alert-1",
    name: "Policy violation tripwire",
    trigger_type: "policy_violation",
    threshold: null,
    agent_id: null,
    channel: "in_app",
    is_active: true,
    trigger_count: 3,
    last_triggered_at: isoMinutesAgo(31),
    created_date: isoDaysAgo(8),
    updated_date: isoMinutesAgo(31),
  },
  {
    id: "seed-alert-2",
    name: "Low operating balance",
    trigger_type: "balance_below",
    threshold: "5000",
    agent_id: "seed-agent-yield",
    channel: "in_app",
    is_active: true,
    trigger_count: 1,
    last_triggered_at: isoDaysAgo(1),
    created_date: isoDaysAgo(11),
    updated_date: isoDaysAgo(1),
  },
];

export const SEED_ALERT_EVENTS = [
  {
    id: "seed-alertevt-1",
    alert_id: "seed-alert-1",
    alert_name: "Policy violation tripwire",
    trigger_type: "policy_violation",
    agent_name: "treasury-rebalancer",
    severity: "critical",
    message: "Agent attempted swap on ethereum — blocked by allowlist guardrail.",
    acknowledged: false,
    created_date: isoMinutesAgo(31),
    updated_date: isoMinutesAgo(31),
  },
  {
    id: "seed-alertevt-2",
    alert_id: "seed-alert-2",
    alert_name: "Low operating balance",
    trigger_type: "balance_below",
    agent_name: "yield-router",
    severity: "warning",
    message: "Operating wallet balance dropped to $4,820 (threshold $5,000).",
    acknowledged: true,
    created_date: isoDaysAgo(1),
    updated_date: isoDaysAgo(1),
  },
];

export const SEED_TEAM_MEMBERS = [
  {
    id: "seed-member-1",
    email: "operator@gctl.local",
    full_name: "Default Operator",
    role: "admin",
    status: "active",
    invited_at: isoDaysAgo(60),
    created_date: isoDaysAgo(60),
    updated_date: isoDaysAgo(60),
  },
  {
    id: "seed-member-2",
    email: "approver@gctl.local",
    full_name: "Risk Approver",
    role: "approver",
    status: "active",
    invited_at: isoDaysAgo(28),
    created_date: isoDaysAgo(28),
    updated_date: isoDaysAgo(28),
  },
  {
    id: "seed-member-3",
    email: "compliance@gctl.local",
    full_name: "Compliance Reviewer",
    role: "viewer",
    status: "invited",
    invited_at: isoDaysAgo(2),
    created_date: isoDaysAgo(2),
    updated_date: isoDaysAgo(2),
  },
];

export const SEED_POLICY_TEMPLATES = POLICY_TEMPLATES.map((t) => ({
  id: t.id,
  name: t.name,
  tagline: t.tagline,
  description: t.description,
  category: t.category,
  tags: t.tags,
  config: t.config,
  source: "builtin",
  uses_count: 0,
  created_date: isoDaysAgo(45),
  updated_date: isoDaysAgo(45),
}));

export const SEED_USER = {
  id: "seed-user-default",
  email: "operator@gctl.local",
  full_name: "Default Operator",
  role: "admin",
};
